version: 2.1


references:

working_directory: &working_directory
  /home/circleci/gitRoot/

repo_cache_key: &repo_cache_key
  v1-repo-{{ .Branch }}-{{ .Revision }}

# Step to restore repository from cache
restore_repo: &restore_repo
  restore_cache:
    key: *repo_cache_key

save_repo: &save_repo
  save_cache:
    key: *repo_cache_key
    paths:
        - *working_directory

jobs: 

  # core job
  build_test_project:

    # assign the working directory
    working_directory: *working_directory
        
    # run the steps with Docker as the primary container
    # job commands run in this container
    # CircleCI Ruby
    # Postgres image
    docker:
      - image: cimg/ruby:2.7.1-node

    # env var assignments

    # steps the core build test job
    steps:

      # check out source code to working directory
      - checkout
      # changing ownership
      - run:
          name: Assigning vars for Git
          command: export EMAIL=circleci@circleci.com && export GIT_AUTHOR_NAME=CircleCi && export GIT_COMMITTER_NAME=CircleCi

      - run:
          name: Initializing
          command: echo initializaing...
                   

      - run: gem install rails 
      - run: yarn --version 
      - run: sudo apt-get update && sudo apt-get install sqlite3 libsqlite3-dev 
      - run: mkdir /home/circleci/appRoot 
      - run: cd /home/circleci/appRoot && bundle gem rubydemo --no-coc --no-mit -t 
      - run: cd /home/circleci/appRoot && rails new rubydemo --force 
      - run: cd /home/circleci/appRoot/rubydemo && yarn add bootstrap jquery popper.js @popperjs/core @fortawesome/fontawesome-free 
      - run: cd /home/circleci/appRoot/rubydemo && rails webpacker:install 
      - run:
          name: Building with testing
          command: echo building with testing...

      - run: cp -r -n /home/circleci/appRoot/rubydemo/ /home/circleci/gitRoot/ 
      - run: cd /home/circleci/gitRoot/rubydemo && export RAILS_ENV=test && rails webpacker:compile 
      - run: cd /home/circleci/gitRoot/rubydemo && export RAILS_ENV=test && rails db:migrate 
      - run: cd /home/circleci/gitRoot/rubydemo && export RAILS_ENV=test && rails db:seed 
      - run: cd /home/circleci/gitRoot/rubydemo && export RAILS_ENV=test && rails test test/controllers 
      # cache the entire project 
      - *save_repo
      # Upload test results for display in Test Summary:
      # https://circleci.com/docs/2.0/collect-test-data/
      - store_test_results:
          path: ~/test-results
      # Upload test summary for display in Artifacts:
      # https://circleci.com/docs/2.0/artifacts/
      - store_artifacts:
          path: ~/test-results/junit


  docker_build:
    # assign the working directory
    working_directory: *working_directory

    docker: # run the steps with Docker, this image is not used and therefore ignored
      - image: circleci/python:3.7  
      
    steps:
      - *restore_repo
      - setup_remote_docker
      - run:
          name: creating docker image..considering using env vars DOCKER_USER and DOCKER_PASS
          command: |
            docker login --username tylertravismya --password 69cutlass 
            docker build -t theharbormaster/ruby-demo:latest -f dockerfile .
            docker push theharbormaster/ruby-demo:latest

# a workflow to build out the environment
workflows:
  build_test_deploy_workflow:
    jobs:
      - build_test_project:
          filters:
            tags:
              only: latest
      - docker_build:
          requires:
            - build_test_project
